"""create core tables

Revision ID: c8fd10fa4d57
Revises: 
Create Date: 2026-08-24 21:08:26.858990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fd10fa4d57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('corridors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('road_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corridors_city_id'), 'corridors', ['city_id'], unique=False)
    op.create_table('intersections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('intersection_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intersections_city_id'), 'intersections', ['city_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_city_id'), 'simulations', ['city_id'], unique=False)
    op.create_index(op.f('ix_simulations_status'), 'simulations', ['status'], unique=False)
    op.create_index(op.f('ix_simulations_user_id'), 'simulations', ['user_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_city_id'), 'zones', ['city_id'], unique=False)
    op.create_table('roads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('road_type', sa.String(length=50), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('lanes', sa.Integer(), nullable=False),
    sa.Column('speed_limit_kmph', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roads_city_id'), 'roads', ['city_id'], unique=False)
    op.create_index(op.f('ix_roads_corridor_id'), 'roads', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_roads_zone_id'), 'roads', ['zone_id'], unique=False)
    op.create_table('traffic_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('phases', sa.JSON(), nullable=True),
    sa.Column('cycle_time_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intersection_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=True),
    sa.Column('intersection_id', sa.Integer(), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_city_id'), 'incidents', ['city_id'], unique=False)
    op.create_index(op.f('ix_incidents_intersection_id'), 'incidents', ['intersection_id'], unique=False)
    op.create_index(op.f('ix_incidents_road_id'), 'incidents', ['road_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('predicted_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_vehicle_count', sa.Integer(), nullable=False),
    sa.Column('predicted_avg_speed_kmph', sa.Float(), nullable=False),
    sa.Column('predicted_congestion_level', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_city_id'), 'predictions', ['city_id'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_for'), 'predictions', ['predicted_for'], unique=False)
    op.create_index(op.f('ix_predictions_road_id'), 'predictions', ['road_id'], unique=False)
    op.create_table('road_intersection',
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('road_id', 'intersection_id')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=True),
    sa.Column('intersection_id', sa.Integer(), nullable=True),
    sa.Column('avg_travel_time_seconds', sa.Float(), nullable=True),
    sa.Column('avg_speed_kmph', sa.Float(), nullable=True),
    sa.Column('total_vehicles', sa.Integer(), nullable=True),
    sa.Column('max_queue_length', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_intersection_id'), 'simulation_results', ['intersection_id'], unique=False)
    op.create_index(op.f('ix_simulation_results_road_id'), 'simulation_results', ['road_id'], unique=False)
    op.create_index(op.f('ix_simulation_results_simulation_id'), 'simulation_results', ['simulation_id'], unique=False)
    op.create_table('traffic_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('avg_speed_kmph', sa.Float(), nullable=False),
    sa.Column('congestion_level', sa.String(length=20), nullable=False),
    sa.Column('vehicle_composition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_records_city_id'), 'traffic_records', ['city_id'], unique=False)
    op.create_index(op.f('ix_traffic_records_road_id'), 'traffic_records', ['road_id'], unique=False)
    op.create_index(op.f('ix_traffic_records_timestamp'), 'traffic_records', ['timestamp'], unique=False)
    op.create_table('emergency_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('origin_intersection_id', sa.Integer(), nullable=False),
    sa.Column('destination_intersection_id', sa.Integer(), nullable=False),
    sa.Column('route_path', sa.JSON(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('estimated_time_seconds', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['destination_intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['origin_intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_routes_city_id'), 'emergency_routes', ['city_id'], unique=False)
    op.create_index(op.f('ix_emergency_routes_destination_intersection_id'), 'emergency_routes', ['destination_intersection_id'], unique=False)
    op.create_index(op.f('ix_emergency_routes_incident_id'), 'emergency_routes', ['incident_id'], unique=False)
    op.create_index(op.f('ix_emergency_routes_origin_intersection_id'), 'emergency_routes', ['origin_intersection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_routes_origin_intersection_id'), table_name='emergency_routes')
    op.drop_index(op.f('ix_emergency_routes_incident_id'), table_name='emergency_routes')
    op.drop_index(op.f('ix_emergency_routes_destination_intersection_id'), table_name='emergency_routes')
    op.drop_index(op.f('ix_emergency_routes_city_id'), table_name='emergency_routes')
    op.drop_table('emergency_routes')
    op.drop_index(op.f('ix_traffic_records_timestamp'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_road_id'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_city_id'), table_name='traffic_records')
    op.drop_table('traffic_records')
    op.drop_index(op.f('ix_simulation_results_simulation_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_road_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_intersection_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_table('road_intersection')
    op.drop_index(op.f('ix_predictions_road_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_predicted_for'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_city_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_incidents_road_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_intersection_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_city_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('traffic_signals')
    op.drop_index(op.f('ix_roads_zone_id'), table_name='roads')
    op.drop_index(op.f('ix_roads_corridor_id'), table_name='roads')
    op.drop_index(op.f('ix_roads_city_id'), table_name='roads')
    op.drop_table('roads')
    op.drop_index(op.f('ix_zones_city_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_simulations_user_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_status'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_city_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_intersections_city_id'), table_name='intersections')
    op.drop_table('intersections')
    op.drop_index(op.f('ix_corridors_city_id'), table_name='corridors')
    op.drop_table('corridors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('cities')
    # ### end Alembic commands ###
